# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black
        pip install coverage
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        git submodule init
        git submodule update
    - name: Lint with Black
      run: |
        # stop the build if there are Python syntax errors or undefined names
        python -m black . --check
    - name: Run unit tests for comparators
      run: |
        python -m unittest discover test/comparator
    - name: Run unit tests for wrappers
      run: |
        python -m unittest discover test/comparator/wrappers
    - name: Run unit tests for findings
      run: |
        python -m unittest discover test/findings
    - name: Run unit tests for detector
      run: |
        python -m unittest discover test/detector
    - name: Run unit tests for CLI
      run: |
        python -m unittest discover test/cli
    - name: Check test coverage
      run: |
        # TODO(xiaozhenliu) improve test coverage to 100
        coverage run -m unittest discover test/comparator && coverage report -m --include=src/comparator/** --fail-under=96
        coverage run -m unittest discover test/comparator/wrappers && coverage report -m --include=src/comparator/wrappers.py --fail-under=96
        coverage run -m unittest discover test/findings && coverage report -m --include=src/findings/** --fail-under=100
        coverage run -m unittest discover test/cli && coverage report -m --include=src/cli/** --fail-under=96
        coverage run -m unittest discover test/detector && coverage report -m --include=src/detector/** --fail-under=95
